# Generated by Django 2.1.5 on 2019-01-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='using_device_number',
            field=models.IntegerField(default=-1),
        ),
    ]
