# Generated by Django 2.1.5 on 2019-01-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_App', '0002_users_using_device_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(default=-1)),
                ('y_position', models.FloatField(default=-1)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='deviceid',
            name='marker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Alert_App.Marker'),
        ),
    ]
