# Generated by Django 2.1.5 on 2019-01-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_App', '0004_marker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='isAlerting',
            field=models.BooleanField(default=False),
        ),
    ]
