# Generated by Django 2.1.5 on 2019-01-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_App', '0006_auto_20190129_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
